### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by gafar-code** [richinsley/comfy2go#12]
I got the err for running example

```panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/richinsley/comfy2go/graphapi.NewPropertyFromInput({0x5d8fd0, 0x1}, 0x0, 0x1?, 0x2)
        C:/Users/Administrator/go/pkg/mod/github.com/richinsley/comfy2go@v0.6.2/graphapi/properties.go:807 +0x619
github.com/richinsley/comfy2go/graphapi.(*NodeObjects).PopulateInputProperties(0xc00005a040)
        C:/Users/Administrator/go/pkg/mod/github.com/richinsley/comfy2go@v0.6.2/graphapi/nodeobjects.go:153 +0x225
github.com/richinsley/comfy2go/client.(*ComfyClient).GetObjectInfos(0xc00009eaf0?)
        C:/Users/Administrator/go/pkg/mod/github.com/richinsley/comfy2go@v0.6.2/client/comfyclientrequests.go:258 +0x105
github.com/richinsley/comfy2go/client.(*ComfyClient).Init(0xc00007e780)
        C:/Users/Administrator/go/pkg/mod/github.com/richinsley/comfy2go@v0.6.2/client/comfyclient.go:146 +0x3d
main.main()
        C:/Users/Administrator/Rnd/comfyui/simple_api.go:60 +0x1f7
exit status 2```

**Comment by dreamfast** [comment]
@gafar-code Please check the PR https://github.com/richinsley/comfy2go/pull/14 it has a fix for this issue that had worked okay for me here.
