### ISSUE TITLE
SIGSEGV on SimpleAPI

### ISSUE THREAD

**Issue by SeditiousSov** [richinsley/comfy2go#4]
2024/02/07 04:52:55 Initialize Client with ID: 9df69f47-9b7e-4080-abff-06142d70c250
2024/02/07 04:52:55 Client 9df69f47-9b7e-4080-abff-06142d70c250 at localhost Queue size: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5394c8]

goroutine 1 [running]:
github.com/richinsley/comfy2go/graphapi.(*Group).IntersectsOrContains(0xdb89453e48?, 0x7fdb407c6140?)
	/projects/ImageGen/pkg/mod/github.com/richinsley/comfy2go@v0.3.0/graphapi/group.go:11 +0x8
github.com/richinsley/comfy2go/graphapi.(*Graph).GetNodesInGroup(0x538b45?, 0xc00021e578?)
	/projects/ImageGen/pkg/mod/github.com/richinsley/comfy2go@v0.3.0/graphapi/graph.go:48 +0x91
github.com/richinsley/comfy2go/graphapi.(*Graph).GetSimpleAPI(0xc0004346c0)
	/projects/ImageGen/pkg/mod/github.com/richinsley/comfy2go@v0.3.0/graphapi/simpleapi.go:21 +0xf6
main.main()
	/projects/ImageGen/src/imagegen.go:80 +0x38a
exit status 2

**Comment by richinsley** [comment]
GetSimpleAPI finds a Group in the workflow that has the title "API".  The nodes contained within the Group are returned as a set of properties:
![image](https://github.com/richinsley/comfy2go/assets/25912281/ef586e34-4627-4db0-bb4a-d6d66693ef4d)

**Comment by dreamfast** [comment]
@SeditiousSov I had to make some code changes to access the properties with the recent updates. This may be of help as a reference on how to access certain properties. In this case `Sampler` and `Positive` would need to be replaced with your titles.

```go
simpleApi := graph.GetNodesInGroup(graph.GetGroupWithTitle("API"))

	for _, v := range simpleApi {
		switch v.Title {

		case "Positive":
			if values, ok := v.WidgetValues.([]interface{}); ok {
				values[0] = message
			}

		case "Sampler":
			if values, ok := v.WidgetValues.([]interface{}); ok {
				values[0] = rand.Intn(999999999999999999)
			}
		}
	}
```

**Comment by richinsley** [comment]
The simple API is designed to take just the first property of each node in the group.  That way, you could group individual properties of different nodes by converting the property to an input:
<img width="1723" alt="Screenshot 2024-03-03 at 11 58 37 AM" src="https://github.com/richinsley/comfy2go/assets/25912281/1322df97-3aca-4abf-9dd9-89aa19cb1497">

Then add a primitive node for that property to api group:
<img width="1724" alt="Screenshot 2024-03-03 at 12 00 54 PM" src="https://github.com/richinsley/comfy2go/assets/25912281/cb6f3916-4e81-4dad-a59d-1c1238dcaaf3">

Then set the Title for the primitive node to the name of the property you want it to be exposed as in the simple api:
<img width="1723" alt="Screenshot 2024-03-03 at 12 03 07 PM" src="https://github.com/richinsley/comfy2go/assets/25912281/d2d0dab8-3182-4a25-8e29-b353aa16328d">

This would result in a Simple API:
{
  "Positive": {
    "Default": "",
    "Multiline": true
  },
  "Seed": {
    "Default": 0,
    "Min": 0,
    "Max": 9223372036854775807,
    "Step": 0
  },
  "aibird_details": {
    "Default": "",
    "Multiline": false
  }
}
